### ISSUE TITLE
Add an example that uses webpack

### ISSUE THREAD

**Issue by jadbox** [BrewhouseTeam/yolk#11]
I've tried several ways to use Yolk along with Webpack + Babel Loader with no luck. I get different cryptic errors whenever I try to start the module compiled with webpack. A lot of this is new to me so it may just be the way I'm setting up this up together.

**Comment by garbles** [comment]
Can you post the error message?

**Comment by garbles** [comment]
Just a guess, but you have to require `rx` before `yolk`. This is definitely a bug.

```
const Rx = require('rx')
const Yolk = require('yolk')
```

**Comment by jadbox** [comment]
I'll give it a shot later today/tomorrow and report back.

**Comment by garbles** [comment]
Alright. As per [this issue](https://github.com/BrewhouseTeam/yolk/issues/12), I'm not very happy with how I'm currently including Rx.

**Comment by garbles** [comment]
You'll no longer receive errors. The version of Rx that the library is using is exposed, i.e.:

```js
const Yolk = require(`yolk`)
const Rx = Yolk.Rx
```
