### ISSUE TITLE
Figure out better way to require Rx

### ISSUE THREAD

**Issue by garbles** [BrewhouseTeam/yolk#12]
I don't have great knowledge of Browserify and I'm not happy with how Rx is being included in the project right now. It's excluded from the bundle so that the user can select while version of Rx they want to use.

In the case of using Yolk with Webpack, however, you deliberately have to require Rx before requiring Yolk for the first time - that sucks.

I tried bundling Rx with Yolk, but I need to figure out what the best way to not include a 500kb file with the distro - that also sucks.

**Comment by jadbox** [comment]
Tricky problem... perhaps you need two types of Yolk builds: one with (latest stable) Rx and one without?

**Comment by garbles** [comment]
Yup. I guess there are two different ways in which this library would be consumed:

1) As a global variable
2) Using something like browserify, webpack or systemjs

In the first case, I can just alias `require('rx')` to the global variable.

In the second case, I'll just run the source code through babel and have "main" in package.json point toward that version of the code instead.

Working on this now. :family:

**Comment by garbles** [comment]
Alright this is fixed.
