### ISSUE TITLE
Add support for Immutable libraries

### ISSUE THREAD

**Issue by garbles** [BrewhouseTeam/yolk#13]
We should implicitly check whether a prop value has a `.toJS` method and call it.

**Comment by ckknight** [comment]
How would I then pass an Immutable.js object as a prop and maintain its immutability? I often use Immutable.Record or even pass an Immutable.Map or Immutable.Set to children and would prefer that it not be coerced to normal Objects and Arrays.

**Comment by garbles** [comment]
thanks for the comment. I think you're misinterpreting what the issue means
to suggest. They would maintain their immutability until just before they
are turned into a vnode. Passing them to composite component children would
not affect them.

**Comment by jadbox** [comment]
How soon are we thinking either Immutable.js or Redux support will be landing? I think this is the last missing piece to start running on Yolk.

**Comment by garbles** [comment]
@jadbox added support for objects that define `.toJS()` to transform themselves into "plain" JavaScript types (see Immutable/Freezer). Also updated the [todo mvc app](https://github.com/BrewhouseTeam/yolk-todomvc) to use Immutable.
